baseURL = "https://berkalpyakici.com/"
languageCode = "en-us"
title = "Berk Alp Yakici"
enableEmoji = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  description = "Berk Alp Yakici's personal webpage."

[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact"
    weight = 10
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    title = "Resume"
    url = "/files/berkalpyakici_resume.pdf"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"
    weight = 30