# Generated by Django 2.2.3 on 2019-07-08 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Work Experience',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('link1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link1_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('link2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link2_icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social Icon'},
        ),
    ]
