# Generated by Django 2.2.3 on 2019-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190708_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('favicon', models.ImageField(default='uploaded_images/favicon.ico', upload_to='uploaded_images/')),
            ],
            options={
                'verbose_name': 'Website General Setting',
            },
        ),
    ]
